name            = "checkin-cron"
main            = "src/index.js"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding      = "DB"
database_name = "checkin-db"
database_id  = "b2c114d3-bda8-47c4-9c83-46391174fcaa"

# Cron：UTC 01:15 = 北京 09:15（上午截止前 15 分钟）
#        UTC 13:45 = 北京 21:45（晚上截止前 15 分钟）
[triggers]
crons = ["15 1 * * 1-5", "30 12 * * 1-5", "45 13 * * 1-5"]
